### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by Trybnetic**
travis works again and coveralls is added.

Do we want other badges?

Look for example at http://shields.io/

### CODE REVIEW

**Comment by Trybnetic** [comment]
Missing badges:
- [ ] https://zenodo.org/

Probably interesting badges:
- [ ] https://landscape.io/

**Comment by dekuenstle** [comment]
Thank's for replacing the only log based coverage test with the more visual coveralls!

Landscape uses tools like pylint (which we use) and aggregates *magically* a number. I'm not sure if this really improves our project, but i think also comes for no cost.
Using zenodo also sounds nice and easy.

So i think both are not that important at this project status, but it will not hurt if you want to try them ;)

**Comment by derNarr** [comment]
+1 für zenodo, see #37

**Comment by Trybnetic** [comment]
@dekuenstle I totally agree with you that the aggregated number is a little weird but landscape also offers a graphical overview of the code quality.

I think it's not necessary but it could be nice to have.

**Comment by Trybnetic** [comment]
In my opinion we can merge this Pull Request after correcting the Version to v0.2.3 and add landscape (if we want) when we do #25 and #14.

Therefore the GUI of landscape could be helpful or what do you think, @derNarr and @dekuenstle?

**Comment by dekuenstle** [comment]
Yes, landscape could help or does at least not harm. So we can give it a try if you want!

**Comment by Trybnetic** [comment]
@dekuenstle would you suggest to add it in this Pull Request or add it as mentioned with #25 and #14?

**Comment by dekuenstle** [comment]
The two issues are about the code itself. This pull request mostly is integrating cloud tools (where landscape the one to measure how well #25 was done). So i would suggest to rename the PR and add zenodo + landscape here.

**Pull request merged**
