### PR TITLE
Develop

### LINKED ISSUE #193: merge develop branch and remove it afterwards
we should simply merge everything into master. For the project of this size this is more appropriate.

### PR DESCRIPTION
**Pull request by derNarr**
Fixes #193  .

Changes proposed in this pull request:
- changes number_of_threads and number_of_processes to n_jobs, which seems to be the parameter name where most scientific software converged to
- some general refactors and code style improvements
- marks software as beta on pypi

### CODE REVIEW

**Comment by Trybnetic** [comment]
Just had a quick overview over the changes. 

- Raising a DeprecationWarning seems appropriate, but I have not checked yet, whether this is done now for all relevant functions
- marking pyndl as beta sounds good to me

Any other things to consider? I will have a deeper review later.

**Comment by Trybnetic** [comment]
`number_of_threads` is still used `learn_inplace_binary_to_binary` in `ndl_openmp.pyx`. This might be fine as `cython.parallel` is also requesting `num_threads`, but using `n_jobs` everywhere then might be better. What do you think?

Another point to consider when making API changes here might be the default settings of `n_jobs`. These seem to be currently not really harmonized. [This](https://scikit-learn.org/stable/glossary.html#term-n_jobs) might be interesting in this context.

I'll update the branch now and wait for you response. The other changes look great!

**Comment by derNarr** [comment]
The default of ``n_jobs`` should be ``None``. If ``n_jobs is None`` it should be set to ``min(n_local_cpus, 8)`` as this should in most cases give good speedups without losing the speed gain on 40 and more cpu machines. What do you think? I like the implementation and meaning of negative numbers as well, which is ``n_local_cpus - negative_number``. ``n_jobs=-1`` would be quite useful default on desktop machines.

**Comment by Trybnetic** [comment]
If we want to be consistent with scikit-learn, then

> n_jobs is None by default, which means unset; it will generally be interpreted as n_jobs=1, unless the current joblib.Parallel backend context specifies otherwise.

From my intuition, I would `n_jobs` expect either to be 1 or to use all cores (=-1) by default, with a tendency to use only one core if not specified. What do you think?

**Comment by derNarr** [comment]
> From my intuition, I would `n_jobs` expect either to be 1 or to use all cores (=-1) by default, with a tendency to use only one core if not specified. What do you think?

Mh, I do feel, I want to have sane defaults, which here would me grab some resources so that it runs fast. Nevertheless, I will merge all the changes so far and move this discussion into an issue, if you are fine with that.

**Review by elnazsh — APPROVED** [review]

**Pull request merged**
