### PR TITLE
fixes errors under Windows by explicitly using utf-8 encoding

### LINKED ISSUE #184: List of changes to consider
> [Note: Tino suggested me to list them here!]

The suggested changes concern the functions `activation()` from the **activation** module, `create_event_file()` and `filter_event_file()` from the **preprocess** module, and `ndl()` from the **ndl** module:

1. Activation:
    + Running with multiple cores doesn’t make the training faster than with one core but actually can make it slightly slower. It seems that `_activation_matrix()` chokes.
    + One suggestion to make things run even faster (even with one core) is to generate batches of events as a matrix and convert to activations using matrix multiplication; i.e., sparse *document-to-term*-like matrix with events in the rows and cues in the columns multiplied by the weight matrix.

2. Reasonable compatibility with MS Windows can be achieved with minimal efforts. A couple of problems that we have detected and which can be easily fixed are:
    + Adding `encoding = 'utf8'` whenever they read or write to a text file. Alternatively, add an argument `encoding` at the top of the functions to let the user choose the encoding. Maybe also allow the user to choose the separator between lines rather than just use `'\t'`.
    + On MS Windows, running `activation()` with multi-threading doesn’t work. You get this error message:
        > "python` windows _pickle.PicklingError: Can't pickle <class 'c_double_Array>".
3. Compatibility with macOS:
    + When using `ndl.ndl()`, `method = 'openmp'` doesn’t work and one can only use `method = 'threading'`. We suggest adding a command line where they detect whether the system is a macOS or not; e.g., something like `if sys.platform == 'darwin'`. Then automatically switch to threading if you have a macOS user.

### PR DESCRIPTION
**Pull request by derNarr**
Fixes #184

### CODE REVIEW

**Comment by Trybnetic** [comment]
Can you briefly explain why encoding is set to `utf-8` explicitly instead of adding it as a key word argument. I did not come up with any example quickly where this is important, but I am also not so much into it. From my gut feeling, using a keyword argument seems also reasonable, so I would be thankful, if you could briefly explain the motivation/intuition behind the proposed changes. 

Further, how can/do we ensure that this actually fixes the errors under Windows?

**Comment by derNarr** [comment]
Windows defaults on a utf-8 encoding. So if we want to have everything in utf-8 than we need to explicitly specify this for Windows. utf-8 is usually the default for Linux and Mac though.

There seems to be even a pep about making utf-8 default in the future for all systems: https://peps.python.org/pep-0686/

**Review by Trybnetic — APPROVED** [review]

**Comment by Trybnetic** [comment]
Are you planning to got to v1.1.0 here?

**Comment by derNarr** [comment]
With these fixes `pyndl` can run the `--no-linux` tests on a Windows 10 virtual machine. This is how I came up with these changes in the first place.

Installation worked only with:

```bash
git clone https://github.com/quantling/pyndl
cd pyndl
poetry install
```

After that I could run:

```
poetry run pytest --no-linux
```

which gave me some error messages. After the changes to the code in this PR every test that is not skipped worked fine.

**Comment by Trybnetic** [comment]
In this case, we should consider adding `windows-latest` to the Github Action.

**Comment by derNarr** [comment]
What was the problem with `windows-latest`, did the installing worked there? If so, I think it would be good to add Windows in the Github Actions. I would go for 1.1.0.

**Comment by Trybnetic** [comment]
Windows testing, at least for the `no-linux` tests seems now to work. Further, I included some maintenance related things into this PR, like fixing the classifiers and setting the upper Python version to test to 3.11 even though this is unrelated to Windows. 

I will set all 6 tests now as future requirements for new PRs or are there any reason to exclude the Windows tests here?

**Comment by Trybnetic** [comment]
I changed the branch protection rules of `main` now accordingly, requiring the checks for python 3.8 and 3.11 to pass for all three operating systems.

**Review by Trybnetic — APPROVED** [review]
I am not sure, whether I am now the right person to review this PR as I also contributed to it, but from my side, it looks fine now. Very nice to have the limited Windows support now!

**Comment by Trybnetic** [comment]
Good point to update the Installation section. As `pyndl` can now be installed on all OS by running

```
pip install --user pyndl 
```

we should consider whether we can remove some of the redundancy and focus more on the troubleshooting.

Further, I think it would be worth to try out whether we now can also build the wheels for Windows in the release workflow.

**Comment by Trybnetic** [comment]
For some reason, the package does not build for python 3.9 under Windows. I will revert the test PyPI upload, but add another workflow for future testing

**Review by Trybnetic — APPROVED** [review]
I am still unsure whether I should review this PR now, but since 40d6c91d5e41215a30d64cd348380f39eea2c8db, the windows builds seem now all to build, so I guess everything that should be achieved in this PR is included now.

**Pull request merged**
